In [113]:
!pip install nbconvert
sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-generic-recommended

SyntaxError: invalid syntax (3122930706.py, line 2)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

C:\Users\DELL\AppData\Roaming\Python\Python310\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [15]:
main_sheet_df = pd.read_csv("Downloads\MAINSHEET.csv")

In [16]:
flood_event_df = pd.read_csv("Downloads\FLOODEVENT.csv")

In [2]:
merged_df = pd.read_csv("Downloads\Merged_DataFrame.csv")

## DATA CLEANING PROCESS

In [4]:
# Replace NaN values with zero in the 'flood' column
merged_df['flood'].fillna(0, inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_19608\1986552447.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_df['flood'].fillna(0, inplace=True)

In [24]:
# Replace NaN values with lagos in the 'location' column
merged_df['Location'].fillna('LAGOS', inplace=True)

In [25]:
merged_df

,name,datetime,tempmax,tempmin,temp,humidity,precip,precipprob,precipcover,preciptype,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility,Location,Dates,flood
0,Lagos,01/01/2019,36.5,25.0,29.4,76.5,0.0,0,0.00,NaN,34.2,16.8,273.9,1014.1,29.6,4.4,LAGOS,NaN,0.0
1,Lagos,01/02/2019,34.1,24.0,28.6,79.7,0.0,0,0.00,NaN,26.6,13.0,205.3,1014.0,32.8,4.4,LAGOS,NaN,0.0
2,Lagos,01/03/2019,34.0,24.9,28.7,79.4,0.0,0,0.00,NaN,28.4,13.9,279.7,1012.8,26.2,4.6,LAGOS,NaN,0.0
3,Lagos,01/04/2019,36.0,24.8,28.9,79.5,0.0,0,0.00,NaN,33.1,15.1,298.5,1012.7,24.4,3.6,LAGOS,NaN,0.0
4,Lagos,01/05/2019,37.0,25.9,28.8,75.0,0.0,0,0.00,NaN,33.8,16.6,229.5,1012.1,14.6,4.0,LAGOS,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2300,Lagos,29/06/2024,31.0,23.9,27.1,87.1,12.0,100,4.17,rain,28.4,22.3,241.1,1012.7,61.8,9.6,LAGOS,NaN,0.0
2301,Lagos,30/06/2024,31.2,25.0,27.8,86.2,3.0,100,4.17,rain,29.5,25.9,236.9,1013.0,62.4,8.5,LAGOS,NaN,0.0
2302,Lagos,01/07/2024,32.0,25.0,27.9,84.6,6.9,100,50.00,rain,24.1,22.3,249.6,1013.5,55.3,10.6,LAGOS,NaN,0.0
2303,Lagos,02/07/2024,30.0,24.0,26.9,85.9,13.6,100,62.50,rain,31.0,22.7,235.8,1012.7,76.9,11.1,LAGOS,NaN,0.0
2304,Lagos,03/07/2024,27.1,24.0,25.4,93.1,52.1,100,79.17,rain,32.4,25.2,224.2,1012.9,76.5,6.7,LAGOS,NaN,0.0

In [26]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2305 entries, 0 to 2304
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              2305 non-null   object
 1   datetime          2305 non-null   object
 2   tempmax           2305 non-null   float64
 3   tempmin           2305 non-null   float64
 4   temp              2305 non-null   float64
 5   humidity          2305 non-null   float64
 6   precip            2305 non-null   float64
 7   precipprob        2305 non-null   int64
 8   precipcover       2305 non-null   float64
 9   preciptype        1542 non-null   object
 10  windgust          2305 non-null   float64
 11  windspeed         2305 non-null   float64
 12  winddir           2305 non-null   float64
 13  sealevelpressure  2305 non-null   float64
 14  cloudcover        2305 non-null   float64
 15  visibility        2301 non-null   float64
 16  Location          2305 non-null   object
 17  Dates             79 non-null     object
 18  flood             2305 non-null   float64
dtypes: float64(13), int64(1), object(5)
memory usage: 342.3+ KB

In [38]:
merged_df.columns

Index(['datetime', 'tempmax', 'tempmin', 'temp', 'humidity', 'precip',
       'precipprob', 'precipcover', 'windgust', 'windspeed', 'winddir',
       'sealevelpressure', 'cloudcover', 'visibility', 'Location', 'flood'],
      dtype='object')

In [43]:
merged_df.describe()

,tempmax,tempmin,temp,humidity,precip,precipprob,precipcover,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility,flood
count,2301.000000,2301.000000,2301.000000,2301.000000,2301.000000,2301.000000,2301.00000,2301.000000,2301.000000,2301.000000,2301.000000,2301.000000,2301.000000,2301.000000
mean,32.074011,24.331465,27.738853,81.757844,4.743590,50.977836,4.96595,29.951890,23.418296,213.584355,1012.039678,54.247805,9.568492,0.034333
std,2.576167,2.086839,1.466167,6.842248,14.459259,50.001304,8.89335,9.594623,12.420537,44.001221,1.716897,12.688494,3.135755,0.182122
min,25.000000,10.000000,23.700000,47.000000,0.000000,0.000000,0.00000,14.800000,7.600000,1.000000,1007.500000,7.200000,1.000000,0.000000
25%,30.000000,23.600000,26.600000,79.500000,0.000000,0.000000,0.00000,24.800000,18.300000,202.500000,1010.800000,47.800000,8.500000,0.000000
50%,32.600000,24.800000,27.900000,82.500000,0.100000,100.000000,4.17000,28.100000,21.600000,219.600000,1012.000000,54.600000,9.600000,0.000000
75%,34.000000,25.300000,28.900000,85.500000,2.000000,100.000000,4.17000,32.000000,25.900000,234.600000,1013.300000,61.400000,10.300000,0.000000
max,54.000000,29.000000,31.300000,98.300000,240.000000,100.000000,95.83000,101.900000,222.500000,359.400000,1017.300000,98.000000,23.800000,1.000000

In [39]:
merged_df.isnull().sum()

datetime            0
tempmax             0
tempmin             0
temp                0
humidity            0
precip              0
precipprob          0
precipcover         0
windgust            0
windspeed           0
winddir             0
sealevelpressure    0
cloudcover          0
visibility          4
Location            0
flood               0
dtype: int64

In [37]:
# drop column
merged_df = merged_df.drop(columns=['Dates'])

In [41]:
#DROP MISSING VALUES
merged_df=merged_df.dropna()

In [ ]:
# CREATE A COPY OF CLEANED DATA

In [61]:
newdf = merged_df.copy()

In [62]:
newdf.columns

Index(['datetime', 'tempmax', 'tempmin', 'temp', 'humidity', 'precip',
       'precipprob', 'precipcover', 'windgust', 'windspeed', 'winddir',
       'sealevelpressure', 'cloudcover', 'visibility', 'Location', 'flood'],
      dtype='object')

In [63]:
newdf

,datetime,tempmax,tempmin,temp,humidity,precip,precipprob,precipcover,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility,Location,flood
0,01/01/2019,36.5,25.0,29.4,76.5,0.0,0,0.00,34.2,16.8,273.9,1014.1,29.6,4.4,LAGOS,0.0
1,01/02/2019,34.1,24.0,28.6,79.7,0.0,0,0.00,26.6,13.0,205.3,1014.0,32.8,4.4,LAGOS,0.0
2,01/03/2019,34.0,24.9,28.7,79.4,0.0,0,0.00,28.4,13.9,279.7,1012.8,26.2,4.6,LAGOS,0.0
3,01/04/2019,36.0,24.8,28.9,79.5,0.0,0,0.00,33.1,15.1,298.5,1012.7,24.4,3.6,LAGOS,0.0
4,01/05/2019,37.0,25.9,28.8,75.0,0.0,0,0.00,33.8,16.6,229.5,1012.1,14.6,4.0,LAGOS,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2300,29/06/2024,31.0,23.9,27.1,87.1,12.0,100,4.17,28.4,22.3,241.1,1012.7,61.8,9.6,LAGOS,0.0
2301,30/06/2024,31.2,25.0,27.8,86.2,3.0,100,4.17,29.5,25.9,236.9,1013.0,62.4,8.5,LAGOS,0.0
2302,01/07/2024,32.0,25.0,27.9,84.6,6.9,100,50.00,24.1,22.3,249.6,1013.5,55.3,10.6,LAGOS,0.0
2303,02/07/2024,30.0,24.0,26.9,85.9,13.6,100,62.50,31.0,22.7,235.8,1012.7,76.9,11.1,LAGOS,0.0
2304,03/07/2024,27.1,24.0,25.4,93.1,52.1,100,79.17,32.4,25.2,224.2,1012.9,76.5,6.7,LAGOS,0.0

## TRAIN MODEL

In [96]:
# Step 1: Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import RandomOverSampler

# Step 2: Preprocess Data
newdf.index = pd.to_datetime(newdf.index)

# Step 3: Prepare the time series data
# Create time-based features
newdf['year'] = newdf.index.year
newdf['month'] = newdf.index.month
newdf['day'] = newdf.index.day
newdf['dayofweek'] = newdf.index.dayofweek

# Define features and target
features = ['tempmax', 'tempmin', 'temp', 'humidity', 'precip', 'precipprob', 
            'precipcover', 'windgust', 'windspeed', 'winddir', 'sealevelpressure', 
            'cloudcover', 'visibility', 'year', 'month', 'day', 'dayofweek']
target = 'flood'

X = newdf[features]
y = newdf[target]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Handle Imbalance using RandomOverSampler
ros = RandomOverSampler(random_state=42)
X_resampled, y_resampled = ros.fit_resample(X_scaled, y)

# Step 5: Use Stratified K-Fold Cross-Validation
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for train_index, test_index in skf.split(X_resampled, y_resampled):
    X_train, X_test = X_resampled[train_index], X_resampled[test_index]
    y_train, y_test = y_resampled[train_index], y_resampled[test_index]

    # Step 6: Build and Train the Logistic Regression Model
    logreg_model = LogisticRegression(max_iter=1000, random_state=42, class_weight='balanced')
    logreg_model.fit(X_train, y_train)
    logreg_y_pred = logreg_model.predict(X_test)

    # Step 7: Evaluate the Model
    print("Logistic Regression Model")
    print(confusion_matrix(y_test, logreg_y_pred))
    print(classification_report(y_test, logreg_y_pred))

# Step 8: Save the trained model for future predictions
import joblib
joblib.dump(logreg_model, 'logistic_regression_flood_model.pkl')

Logistic Regression Model
[[326  51  22   0   0   0   0]
 [ 69 330   0   0   0   0   0]
 [  0   0 399   0   0   0   0]
 [  0   0   0 399   0   0   0]
 [  0   0   0   0 399   0   0]
 [  0   0   0   0   0 398   0]
 [  0   0   0   0   0   0 399]]
              precision    recall  f1-score   support

         0.0       0.83      0.82      0.82       399
         1.0       0.87      0.83      0.85       399
         2.0       0.95      1.00      0.97       399
         5.0       1.00      1.00      1.00       399
         6.0       1.00      1.00      1.00       399
        21.0       1.00      1.00      1.00       398
        25.0       1.00      1.00      1.00       399

    accuracy                           0.95      2792
   macro avg       0.95      0.95      0.95      2792
weighted avg       0.95      0.95      0.95      2792

Logistic Regression Model
[[335  47  17   0   0   0   0]
 [ 59 340   0   0   0   0   0]
 [  0   0 398   0   0   0   0]
 [  0   0   0 399   0   0   0]
 [  0   0   0   0 399   0   0]
 [  0   0   0   0   0 399   0]
 [  0   0   0   0   0   0 399]]
              precision    recall  f1-score   support

         0.0       0.85      0.84      0.84       399
         1.0       0.88      0.85      0.87       399
         2.0       0.96      1.00      0.98       398
         5.0       1.00      1.00      1.00       399
         6.0       1.00      1.00      1.00       399
        21.0       1.00      1.00      1.00       399
        25.0       1.00      1.00      1.00       399

    accuracy                           0.96      2792
   macro avg       0.96      0.96      0.96      2792
weighted avg       0.96      0.96      0.96      2792

Logistic Regression Model
[[303  69  27   0   0   0   0]
 [ 67 331   0   0   0   0   0]
 [  0   0 399   0   0   0   0]
 [  0   0   0 399   0   0   0]
 [  0   0   0   0 399   0   0]
 [  0   0   0   0   0 399   0]
 [  0   0   0   0   0   0 399]]
              precision    recall  f1-score   support

         0.0       0.82      0.76      0.79       399
         1.0       0.83      0.83      0.83       398
         2.0       0.94      1.00      0.97       399
         5.0       1.00      1.00      1.00       399
         6.0       1.00      1.00      1.00       399
        21.0       1.00      1.00      1.00       399
        25.0       1.00      1.00      1.00       399

    accuracy                           0.94      2792
   macro avg       0.94      0.94      0.94      2792
weighted avg       0.94      0.94      0.94      2792

Logistic Regression Model
[[311  62  26   0   0   0   0]
 [  0 399   0   0   0   0   0]
 [  0   0 399   0   0   0   0]
 [  0   0   0 398   0   0   0]
 [  0   0   0   0 398   0   0]
 [  0   0   0   0   0 399   0]
 [  0   0   0   0   0   0 399]]
              precision    recall  f1-score   support

         0.0       1.00      0.78      0.88       399
         1.0       0.87      1.00      0.93       399
         2.0       0.94      1.00      0.97       399
         5.0       1.00      1.00      1.00       398
         6.0       1.00      1.00      1.00       398
        21.0       1.00      1.00      1.00       399
        25.0       1.00      1.00      1.00       399

    accuracy                           0.97      2791
   macro avg       0.97      0.97      0.97      2791
weighted avg       0.97      0.97      0.97      2791

Logistic Regression Model
[[315  57  26   0   0   0   0]
 [  0 399   0   0   0   0   0]
 [  0   0 399   0   0   0   0]
 [  0   0   0 399   0   0   0]
 [  0   0   0   0 399   0   0]
 [  0   0   0   0   0 399   0]
 [  0   0   0   0   0   0 398]]
              precision    recall  f1-score   support

         0.0       1.00      0.79      0.88       398
         1.0       0.88      1.00      0.93       399
         2.0       0.94      1.00      0.97       399
         5.0       1.00      1.00      1.00       399
         6.0       1.00      1.00      1.00       399
        21.0       1.00      1.00      1.00       399
        25.0       1.00      1.00      1.00       398

    accuracy                           0.97      2791
   macro avg       0.97      0.97      0.97      2791
weighted avg       0.97      0.97      0.97      2791

['logistic_regression_flood_model.pkl']

## PREDICT PROBAB;E DATE

In [111]:
# Import necessary libraries
import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler

# Load the future weather data
future_weather_data = pd.read_csv('Downloads\lagos nigeria 2024-07-07 to 2024-12-31.csv')

# Ensure the datetime column is correctly formatted with dayfirst=True
future_weather_data['datetime'] = pd.to_datetime(future_weather_data['datetime'], dayfirst=True)
future_weather_data.set_index('datetime', inplace=True)

# Create time-based features for future data
future_weather_data['year'] = future_weather_data.index.year
future_weather_data['month'] = future_weather_data.index.month
future_weather_data['day'] = future_weather_data.index.day
future_weather_data['dayofweek'] = future_weather_data.index.dayofweek

# Define features
features = ['tempmax', 'tempmin', 'temp', 'humidity', 'precip', 'precipprob', 
            'precipcover', 'windgust', 'windspeed', 'winddir', 'sealevelpressure', 
            'cloudcover', 'visibility', 'year', 'month', 'day', 'dayofweek']

# Ensure future data aligns with the features used in the model
X_future = future_weather_data[features]

# Load the trained model and scaler
logreg_model = joblib.load('logistic_regression_flood_model.pkl')
scaler = joblib.load('scaler.pkl')

# Scale the future data
X_future_scaled = scaler.transform(X_future)

# Predict flood incidences
future_flood_prediction = logreg_model.predict(X_future_scaled)

# Find the next probable date of flood
next_flood_date = future_weather_data[future_flood_prediction == 1].index.min()
print("Next probable date of flood:", next_flood_date)

Next probable date of flood: 2024-07-13 00:00:00